# Generated by Django 4.2.6 on 2023-10-05 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SplitAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owe_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "owe_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owe_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owe_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owe_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("owe_by", "owe_from")},
            },
        ),
    ]
